

# Based on official ELIGOS2 installation guide: https://gitlab.com/piroonj/eligos2
# Uses mambaorg/micromamba for faster dependency resolution


ARG VERSION=2.2.0
FROM piroonj/eligos2:v${VERSION}

RUN eligos2 --help 
