name: rnamodivt|[Systematic calibration of epitranscriptomic maps using a synthetic modification-free RNA library](https://www.nature.com/articles/s41592-021-01280-7)

on:
  push:
    paths:
      - 'tools/rnamodivt/**'
      - '.github/workflows/tools_rnamodivt_build.yaml'
  workflow_dispatch:


jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 48df2c04ee063c96aaefde64df915a867528f93e

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ secrets.DH_USER }}/rnamodivt
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DH_USER }}
          password: ${{ secrets.DH_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./tools/rnamodivt/
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DH_USER }}/rnamodivt:${{ matrix.version }}
          build-args: VERSION=${{ matrix.version }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ secrets.DH_USER }}/rnamodivt:cache
          cache-to: type=registry,ref=${{ secrets.DH_USER }}/rnamodivt:cache,mode=max
