name: rmats|[Multivariate Analysis of Transcript Splicing (MATS)](https://rnaseq-mats.sourceforge.io/)

on:
  push:
    paths:
      - 'tools/rmats/**'
      - '.github/workflows/tools_rmats_build.yaml'
  workflow_dispatch:

env:
  REGISTRY_IMAGE: ${{ secrets.DH_USER }}/rmats 
  WORK_PATH: ./tools/rmats/


jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 4.3.0
          - 4.2.0
          - 4.1.2
          - 4.1.1
          - 4.1.0
          - 4.0.2
          - 3.2.5


    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ secrets.DH_USER }}/stringtie
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DH_USER }}
          password: ${{ secrets.DH_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./tools/stringtie/
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DH_USER }}/stringtie:${{ matrix.version }}
          build-args: VERSION=${{ matrix.version }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ secrets.DH_USER }}/stringtie:cache
          cache-to: type=registry,ref=${{ secrets.DH_USER }}/stringtie:cache,mode=max
