name: image build for nanopolish container

on:
  push:
    paths:
      - 'tools/nanopolish/**'
  workflow_dispatch:


jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 0.14.0
          - 0.13.3

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ secrets.DH_USER }}/nanopolish
          # generate Docker tags based on the following events/attributes
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DH_USER }}
          password: ${{ secrets.DH_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./tools/nanopolish/
          platforms: linux/arm64,linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DH_USER }}/nanopolish:${{ matrix.version }}
          build-args: VERSION=${{ matrix.version }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ secrets.DH_USER }}/nanopolish:cache
          cache-to: type=registry,ref=${{ secrets.DH_USER }}/nanopolish:cache,mode=max
          
