name: tape|[Deep autoencoder for interpretable tissue-adaptive deconvolution and cell-type-specific gene analysis](https://www.nature.com/articles/s41467-022-34550-9)

on:
  push:
    paths:
      - 'tools/tape/**'
  workflow_dispatch:


jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 1.1.2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ secrets.DH_USER }}/tape
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DH_USER }}
          password: ${{ secrets.DH_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./tools/tape/
          platforms: linux/arm64,linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DH_USER }}/tape:${{ matrix.version }}
          build-args: VERSION=${{ matrix.version }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ secrets.DH_USER }}/tape:cache
          cache-to: type=registry,ref=${{ secrets.DH_USER }}/tape:cache,mode=max
