name: vg|[Variation graph toolkit improves read mapping by representing genetic variation in the reference](https://www.nature.com/articles/nbt.4227)

on:
  push:
    paths:
      - 'tools/vg/**'
      - '.github/workflows/tools_vg_build.yaml'
  workflow_dispatch:


jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 1.38.0
          - 1.42.0
          - 1.23.0
          - 1.63.1
          - 1.61.0

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ secrets.DH_USER }}/vg
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DH_USER }}
          password: ${{ secrets.DH_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./tools/vg/
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DH_USER }}/vg:${{ matrix.version }}
          build-args: VERSION=${{ matrix.version }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ secrets.DH_USER }}/vg:cache
          cache-to: type=registry,ref=${{ secrets.DH_USER }}/vg:cache,mode=max
